Remove Firefox workaround added in 2015
This was added in 2c1576a1de22dcfe62878 ("Support fixtures in tests") in
March of 2015. I tested it in Firefox today (February 2019) and
everything seems rosy. This is worth trying to remove because the
textual content in the DOM can trigger some edge cases and lead to test
failures like this one:

```
AssertionError: expected '<p>link <a href="http://www.liferay.com">www.liferay.com</a> </p>' to equal '<p>link <a href="http://www.liferay.com">www.liferay.com</a></p>'
```

(Note the whitespace).

As a bonus, things look cleaner without the workaround.