fix: "no ssl bump domain(s) not valid"
Fixes CI errors such as:

    Error: no ssl bump domains(s) not valid, invalid domain(s): -B all

seen here:

    https://travis-ci.org/liferay/alloy-editor/builds/561028047

This is similar to the fix that we did on the "master" branch in
b3beb1e984066503d1070f253 ("Update karma-sauce-launcher as recommended
by `npm audit`, 15 Jan 2019).