fix: broken website builds due to malformed Markdown (#1204)
`yarn build` was dying with:

```
error Plugin gatsby-mdx returned an error

  SyntaxError: unknown: Expected corresponding JSX closing tag for <MDXTag> (4:0)
```

Closes: https://github.com/liferay/alloy-editor/issues/1204